### ISSUE TITLE
QTLseq plot error

### ISSUE THREAD

**Issue by Haritha-gen** [YuSugihara/QTL-seq#14]
Hi, I am getting the following error in QTLseq pipeline, Please help to resolve

[QTL-seq:2020-12-17 14:11:25] indexing VCF successfully finished.
Traceback (most recent call last):
  File "/home/haritha/.local/bin/qtlplot", line 11, in <module>
    load_entry_point('qtlseq', 'console_scripts', 'qtlplot')()
  File "/home/haritha/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/haritha/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/haritha/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/haritha/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/haritha/QTL-seq/qtlseq/qtlplot.py", line 31
    flush=True)
         ^
SyntaxError: invalid syntax
[QTL-seq:2020-12-17 14:11:26] QTL-seq successfully finished.

**Comment by YuSugihara** [comment]
QTL-seq depends on Python version 3 as described in README on Github page.
Therefore, please update your python from version 2 to 3.
After that, please confirm whether the test data set successfully finishes.
