### ISSUE TITLE
RuntimeError and EOFError

### ISSUE THREAD

**Issue by Yoshio-yoshioka** [YuSugihara/QTL-seq#16]
Hello, I am trying to perform QTL-seq using the test data (https://github.com/YuSugihara/QTL-seq/tree/master/test) in the miniconda virtual environment.
But the process does not start and encounters the error messages below.
Could you give some suggestions? Thanks in advance.
 
```{terminal}
(qtlseq) yoshio@iMac 210209_test % ./qtlseq.sh
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/yoshio/miniconda3/envs/qtlseq/bin/qtlseq", line 7, in <module>
    from qtlseq.qtlseq import main
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/site-packages/qtlseq/qtlseq.py", line 18, in <module>
    from qtlseq.mpileup import Mpileup
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/site-packages/qtlseq/mpileup.py", line 7, in <module>
    from qtlseq.vcf2index import Vcf2Index
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/site-packages/qtlseq/vcf2index.py", line 10, in <module>
    cache = Manager().dict()
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/managers.py", line 553, in start
    self._process.start()
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/yoshio/miniconda3/envs/qtlseq/bin/qtlseq", line 7, in <module>
    from qtlseq.qtlseq import main
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/site-packages/qtlseq/qtlseq.py", line 18, in <module>
    from qtlseq.mpileup import Mpileup
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/site-packages/qtlseq/mpileup.py", line 7, in <module>
    from qtlseq.vcf2index import Vcf2Index
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/site-packages/qtlseq/vcf2index.py", line 10, in <module>
    cache = Manager().dict()
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/managers.py", line 557, in start
    self._address = reader.recv()
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/Users/yoshio/miniconda3/envs/qtlseq/lib/python3.9/multiprocessing/connection.py", line 388, in _recv
    raise EOFError
EOFError
```

**Comment by YuSugihara** [comment]
Sorry for my late reply.

$ ./qtlseq.sh
doesn't recognize the script as shell command because this file doesn't have "Shebang" (https://en.wikipedia.org/wiki/Shebang_(Unix)).

$ sh ./qtlseq.sh is corrrect

Or, you can copy and paste the lines inside of "qtlseq.sh".
