### ISSUE TITLE
QTLplot error calculating snp index error

### ISSUE THREAD

**Issue by Brent-Saylor-Canopy** [YuSugihara/QTL-seq#20]
Hi,

I am running QTLseq from bams and I get the following error with the following code. 

The bams have all been mapped with bwa mem then run through the following picard modules CleanSam, FixMateInformation, AddOrReplaceReadGroups, and MarkDuplicatesWithMateCigar

```
qtlseq -r refrence.fasta  -p parent_cleaned_fixed_group_DEDUP.bam -b1 ../Bulk1_cleaned_fixed_group_DEDUP.bam -b2 ../Bulk2_cleaned_fixed_group_DEDUP.bam -n1 38 -n2 38  -o ../QTLseq_output
[QTL-seq:2021-04-25 15:02:54] start to run QTL-seq.
[QTL-seq:2021-04-25 15:02:54] maximum number of threads which you can use is up to 32.
[QTL-seq:2021-04-25 15:02:54] start to index reference fasta.
[QTL-seq:2021-04-25 15:18:39] indexing of reference successfully finished.
[QTL-seq:2021-04-25 15:18:39] start to merge BAMs.
[QTL-seq:2021-04-25 19:37:00] merging process successfully finished.
[QTL-seq:2021-04-25 19:37:00] start to call variants.
[QTL-seq:2021-04-25 20:00:14] variant calling successfully finished.
[QTL-seq:2021-04-25 20:00:14] start to index VCF.
[QTL-seq:2021-04-25 20:00:15] indexing VCF successfully finished.
[QTL-seq:2021-04-25 20:00:15] start to run QTL-plot.
[QTL-seq:2021-04-25 20:00:15] maximum number of threads which you can use is up to 32.
[QTL-seq:2021-04-25 20:00:15] start to calculate SNP-index.
Traceback (most recent call last):
  File "/home/cgc-genomics-admin/miniconda3/envs/BULK_QTL_env/bin/qtlplot", line 10, in <module>
    sys.exit(main())
  File "/home/cgc-genomics-admin/miniconda3/envs/BULK_QTL_env/lib/python3.9/site-packages/qtlseq/qtlplot.py", line 207, in main
    qp.run()
  File "/home/cgc-genomics-admin/miniconda3/envs/BULK_QTL_env/lib/python3.9/site-packages/qtlseq/qtlplot.py", line 192, in run
    v2i.run()
  File "/home/cgc-genomics-admin/miniconda3/envs/BULK_QTL_env/lib/python3.9/site-packages/qtlseq/vcf2index.py", line 342, in run
    self.field_pos = self.get_field()
  File "/home/cgc-genomics-admin/miniconda3/envs/BULK_QTL_env/lib/python3.9/site-packages/qtlseq/vcf2index.py", line 130, in get_field
    return GT_pos, AD_pos, ADF_pos, ADR_pos
UnboundLocalError: local variable 'GT_pos' referenced before assignment
[QTL-seq:2021-04-25 20:00:15] QTL-seq successfully finished.

```

**Comment by Brent-Saylor-Canopy** [comment]
After taking a closer look at the VCF file, it appears to be empty of any SNPs.

**Comment by zhachengwan** [comment]
Excuse me, have you solved this problem? I've encountered the same problem too. I'd appreciate it if you could offer some advice.
