### ISSUE TITLE
QTLseq package not found error

### ISSUE THREAD

**Issue by Nikhilasai1223** [YuSugihara/QTL-seq#22]
[QTL-seq:2021-06-14 16:33:29] start to run QTL-seq.
[QTL-seq:2021-06-14 16:33:29] maximum number of threads which you can use is up to 16.
[QTL-seq:2021-06-14 16:33:29] start to index reference fasta.
[QTL-seq:2021-06-14 16:38:21] indexing of reference successfully finished.
[QTL-seq:2021-06-14 16:38:21] start to filter reads.
[QTL-seq:2021-06-14 16:58:13] filtering process successfully finished.
[QTL-seq:2021-06-14 16:58:13] start to merge BAMs.
[QTL-seq:2021-06-14 17:14:38] merging process successfully finished.
[QTL-seq:2021-06-14 17:14:38] start to call variants.
[QTL-seq:2021-06-14 17:35:02] variant calling successfully finished.
[QTL-seq:2021-06-14 17:35:02] start to index VCF.
[QTL-seq:2021-06-14 17:35:04] indexing VCF successfully finished.
Traceback (most recent call last):
  File "/home/hkplab/anaconda2/bin/qtlplot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/hkplab/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/hkplab/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/hkplab/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/hkplab/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/hkplab/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/hkplab/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'qtlseq' distribution was not found and is required by the application
[QTL-seq:2021-06-14 17:35:09] QTL-seq successfully finished.

please help me with this error.

**Comment by YuSugihara** [comment]
It seems that you are using Python2.
QTL-seq required Python3.
