### ISSUE TITLE
Image size related error

### ISSUE THREAD

**Issue by shanmugavadivelps** [YuSugihara/QTL-seq#25]
Hi sir,
I have run qtlseq with vcf file and getting error related to image size. I am providing the errors observed during the run for your intervention.
Help me to solve this.

[QTL-seq:2021-06-23 22:04:16] start to run QTL-plot.
[QTL-seq:2021-06-23 22:04:16] maximum number of threads which you can use is up to 40.
[QTL-seq:2021-06-23 22:04:16] start to calculate SNP-index.
[QTL-seq:2021-06-23 22:04:17] no ADF or ADR field in your VCF.
[QTL-seq:2021-06-23 22:04:17] strand bias filter will be skipped.
[QTL-seq:2021-06-23 22:19:18] SNP-index successfully finished.
[QTL-seq:2021-06-23 22:19:18] start to smooth SNP-index.
[QTL-seq:2021-06-23 22:19:24] smoothing process successfully finished.
[QTL-seq:2021-06-23 22:19:24] plotting now...
Traceback (most recent call last):
  File "/home/iipruser/yes/bin/qtlplot", line 10, in <module>
    sys.exit(main())
  File "/home/iipruser/yes/lib/python3.8/site-packages/qtlseq/qtlplot.py", line 208, in main
    qp.run()
  File "/home/iipruser/yes/lib/python3.8/site-packages/qtlseq/qtlplot.py", line 197, in run
    pt.run()
  File "/home/iipruser/yes/lib/python3.8/site-packages/qtlseq/plot.py", line 268, in run
    self.plot_bulk1_SNPindex()
  File "/home/iipruser/yes/lib/python3.8/site-packages/qtlseq/plot.py", line 140, in plot_bulk1_SNPindex
    plt.savefig('{}/bulk1_SNPindex.{}'.format(self.out, self.args.format))
  File "/home/iipruser/yes/lib/python3.8/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/iipruser/yes/lib/python3.8/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/iipruser/yes/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2210, in print_figure
    result = print_method(
  File "/home/iipruser/yes/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/iipruser/yes/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 509, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/iipruser/yes/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/home/iipruser/yes/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 418, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/home/iipruser/yes/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 96, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 1500x1245600 pixels is too large. It must be less than 2^16 in each direction.

**Comment by sangeeta10mar** [comment]
I am facing the same issue, please help

**Comment by redw0lf11** [comment]
hi @sangeeta10mar 
For image related error coming with "pixel is too large",just go to the QTL-seq installed directory and in  plot.py file make changes in self.fig_width or self.fig_height as per your requirement or optimize with other parameters in this file. plot.py mainly important for plotting the image.

**Comment by sangeeta10mar** [comment]
Thanks, I will try and then let you know.

**Comment by YuSugihara** [comment]
I am sorry for my late reply.

Basically, image size related error comes from contiguous reference genome because QTL-seq tries to plot each chromosome or contig to each panel.

Recently, we implemented to plot only significant chromosome or contigs when QTL-seq faced this error.
So maybe you can try the lates version of QTL-seq
