### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'QTLseq/snp_index.tsv.temp'

### ISSUE THREAD

**Issue by WangWaud** [YuSugihara/QTL-seq#32]
Hi,
I got an error when using QTL-seq.It said "FileNotFoundError: [Errno 2] No such file or directory: 'QTLseq/snp_index.tsv.temp'",but the temp shouldn't be created by the software?I don't know why.

Below is Traceback and error
`
Traceback (most recent call last):
  File "/home/zwang/anaconda3/envs/SNP/bin/qtlplot", line 10, in <module>
    sys.exit(main())
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/qtlseq/qtlplot.py", line 208, in main
    qp.run()
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/qtlseq/qtlplot.py", line 193, in run
    v2i.run()
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/qtlseq/vcf2index.py", line 343, in run
    self.calculate_SNPindex()
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/qtlseq/vcf2index.py", line 338, in calculate_SNPindex
    self.table_sort()
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/qtlseq/vcf2index.py", line 297, in table_sort
    'delta_SNPindex'])
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/pandas/io/parsers.py", line 610, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/pandas/io/parsers.py", line 462, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/pandas/io/parsers.py", line 819, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/pandas/io/parsers.py", line 1050, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/pandas/io/parsers.py", line 1867, in __init__
    self._open_handles(src, kwds)
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/pandas/io/parsers.py", line 1368, in _open_handles
    storage_options=kwds.get("storage_options", None),
  File "/home/zwang/anaconda3/envs/SNP/lib/python3.7/site-packages/pandas/io/common.py", line 647, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'QTLseq/snp_index.tsv.temp'
`

My command is 
`
qtlplot -v ./ZM895_Rbuk_Sbuk_merged.vcf.gz \
         -o QTLseq \
         -n1 30 \
         -n2 30 \
         -F 2 \
         --species Wheat \
         -w 2000 \
         -s 200
`

The vcf file "ZM895_Rbuk_Sbuk_merged.vcf.gz" contains AD format and three columns of parent, bulk1 and bulk2 in this order.And I have created the output file folder QTLseq.

The vcf file is like 
`
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  ZM895_FRAS220033950-2r  ZM-Rbuk_FRAS220033948-2r        ZM-Sbuk_FRAS220033949-2r
1A      7638    .       A       C       213.78  .       BaseQRankSum=2.638;ClippingRankSum=-0;ExcessHet=3.0103;FS=0;MQ=60;MQRankSum=-0;QD=21.38;ReadPosRankSum=0.61;SOR=0.569;DP=10;AF=0.5;MLEAC=1;MLEAF=0.5;AN=2;AC=1  GT:AD:DP:GQ:PL  ./.:.:.:.:.     0/1:3,7:10:25:242,0,25  ./.:.:.:.:.`

Thanks!

**Comment by YuSugihara** [comment]
I am sorry for my late reply.
Did you check the markers in VCF?

At least, the line that you pasted has missing genotype.

**Comment by WangWaud** [comment]
It's a data merged by 3 vcf(parent,bulk1 and bulk2).I think just some SNPs has missing genotype.
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/82741778/163412197-cdb44312-db65-4ab5-801f-300b1b863478.png">

**Comment by YuSugihara** [comment]
At least, the SNPs in the screenshot cannot be used in QTL-seq.
For example, QTL-seq retains the SNPs that are homozygous in the parent.
The regions in the screenshot looks heterozygous.
