### ISSUE TITLE
SystemError: tile cannot extend outside image

### ISSUE THREAD

**Issue by highwire2021** [YuSugihara/QTL-seq#33]
Hi,
Many thanks to the developers.
I used use the mutmap v2.3.3 and showed "MutMap successfully finished". But the message "SystemError: tile cannot extend outside image" showed in the last line. I don't know how to deal with it.

Could you help me?

Best wishes!

**Comment by YuSugihara** [comment]
I am sorry for my late response.

Would you share the VCF file in 30_vcf with the command line that you ran?

**Comment by highwire2021** [comment]
Thank you. 
The command and result as follows:
~/mutmap$ mutmap -r ref.fasta -c P7_CleanData_R1.fastq.gz,P7_CleanData_R1.fastq.gz -b R151_L2_137A37.R1.fastq.gz,R151_L2_137A37.R2.fastq.gz -n 30  -o outR151  -t 12 --species  Rice
[MutMap:2022-06-09 16:17:47] start to run MutMap.
[MutMap:2022-06-09 16:17:47] maximum number of threads which you can use is up to 16.
[MutMap:2022-06-09 16:17:47] start to index reference fasta.
[MutMap:2022-06-09 16:21:27] indexing of reference successfully finished.
[MutMap:2022-06-09 16:21:27] start to align reads of cultivar.0000 by BWA.
[MutMap:2022-06-09 16:53:04] alignment cultivar.0000 successfully finished.
[MutMap:2022-06-09 16:53:04] start to align reads of bulk.0000 by BWA.
[MutMap:2022-06-09 17:41:21] alignment bulk.0000 successfully finished.
[MutMap:2022-06-09 17:41:21] start to merge BAMs.
[MutMap:2022-06-09 17:42:50] merging process successfully finished.
[MutMap:2022-06-09 17:42:50] start to call variants.
[MutMap:2022-06-09 17:46:47] variant calling successfully finished.
[MutMap:2022-06-09 17:46:47] start to index VCF.
[MutMap:2022-06-09 17:46:47] indexing VCF successfully finished.
[MutMap:2022-06-09 17:46:48] start to run MutPlot.
!!WARNING!! Number of replicates for simulation is not enough to consider multiple testing correction. Therefore, the highest SNP-index and the second highest SNP-index were selected for p99 and p95, respectively.
[MutMap:2022-06-09 17:46:48] start to calculate SNP-index.
[MutMap:2022-06-09 17:46:48] SNP-index successfully finished.
[MutMap:2022-06-09 17:46:48] start to smooth SNP-index.
[MutMap:2022-06-09 17:46:48] smoothing process successfully finished.
[MutMap:2022-06-09 17:46:48] plotting now...
Traceback (most recent call last):
  File "/home/wdk/miniconda3/envs/mutmap/bin/mutplot", line 10, in <module>
    sys.exit(main())
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/mutmap/mutplot.py", line 189, in main
    mp.run()
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/mutmap/mutplot.py", line 178, in run
    pt.run()
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/mutmap/plot.py", line 164, in run
    plt.savefig('{}/mutmap_plot.{}'.format(self.out, self.args.format))
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/matplotlib/pyplot.py", line 979, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/matplotlib/figure.py", line 3046, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 541, in print_png
    mpl.image.imsave(
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/matplotlib/image.py", line 1675, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/PIL/Image.py", line 2300, in save
    save_handler(self, fp, filename)
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 1374, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/wdk/miniconda3/envs/mutmap/lib/python3.10/site-packages/PIL/ImageFile.py", line 510, in _save
    encoder.setimage(im.im, b)
SystemError: tile cannot extend outside image
[MutMap:2022-06-09 17:46:49] MutMap successfully finished.

**Comment by YuSugihara** [comment]
Sorry for my late response.

Would you remove the option "--species Rice" and try mutplot from VCF file?
We implemented that option into QTL-seq, but the results may change from what we expect.
