### ISSUE TITLE
Errors related to multiprocessing 

### ISSUE THREAD

**Issue by Abieskawa** [YuSugihara/QTL-seq#40]
I am a Mac M2 chip user. When I use this program on the test files, it goes wrong in the variant calling stage. Could you help me fix the problem? Thanks.
The below is error message:
`Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "/Users/kenhsu/anaconda3/envs/py3.11/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/kenhsu/anaconda3/envs/py3.11/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/kenhsu/anaconda3/envs/py3.11/lib/python3.11/multiprocessing/pool.py", line 114, in worker
    task = get()
           ^^^^^
  File "/Users/kenhsu/anaconda3/envs/py3.11/lib/python3.11/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kenhsu/QTL-seq/qtlseq/mpileup.py", line 7, in <module>
    from qtlseq.vcf2index import Vcf2Index
  File "/Users/kenhsu/QTL-seq/qtlseq/vcf2index.py", line 10, in <module>
    cache = Manager().dict()
            ^^^^^^^^^
  File "/Users/kenhsu/anaconda3/envs/py3.11/lib/python3.11/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/kenhsu/anaconda3/envs/py3.11/lib/python3.11/multiprocessing/managers.py", line 563, in start
    self._process.start()
  File "/Users/kenhsu/anaconda3/envs/py3.11/lib/python3.11/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: daemonic processes are not allowed to have children
`

**Comment by YuSugihara** [comment]
Sorry for my late response.

Thank you very much for reporting the error.

I actually found an error related to multiprocessing on Mac which I could not observe in Linux.
I have already fixed this bug and have released as v2.2.3.
I'm not sure if this error is relevant to your error, but I could find this error from your report.

Again, thank you very much for your report.

Best regards,
Yu
