### ISSUE TITLE
call_log function from utils.py try to write in a not existing file

### ISSUE THREAD

**Issue by jdalino** [YuSugihara/QTL-seq#48]
Hello,

Here is the error:

```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/mpileup.py", line 140, in mpileup
    sbp.run(cmd1,
  File "/envQtlseq/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r ref -f /Test_output/10_ref/ref.fasta --ignore-RG /Test_output/20_bam/parent.bam /Test_output/20_bam/bulk1.bam /Test_output/20_bam/bulk2.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o /Test_output/30_vcf/qtlseq.ref.vcf.gz >> /Test_output/log/bcftools.ref.log 2>&1' returned non-zero exit status 127.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/envQtlseq/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/envQtlseq/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/mpileup.py", line 146, in mpileup
    call_log(self.out, 'bcftools', cmd1)
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/utils.py", line 20, in call_log
    with open('{}/log/{}.log'.format(out_dir, name)) as log:
FileNotFoundError: [Errno 2] No such file or directory: '/Test_output/log/bcftools.log'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/envQtlseq/bin/qtlseq", line 10, in <module>
    sys.exit(main())
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/qtlseq.py", line 171, in main
    QTLseq(args).run()
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/qtlseq.py", line 166, in run
    self.mpileup()
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/qtlseq.py", line 122, in mpileup
    mp.run()
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/mpileup.py", line 228, in run
    p.map(self.mpileup, chr_names)
  File "/envQtlseq/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/envQtlseq/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/Test_output/log/bcftools.log'
```

The first error is caused by a library compatibility problem in my bcftools installation (that I can deal with).

The problem here is the 
```
Traceback (most recent call last):
  File "/envQtlseq/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/envQtlseq/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/mpileup.py", line 146, in mpileup
    call_log(self.out, 'bcftools', cmd1)
  File "/envQtlseq/lib/python3.10/site-packages/qtlseq/utils.py", line 20, in call_log
    with open('{}/log/{}.log'.format(out_dir, name)) as log:
FileNotFoundError: [Errno 2] No such file or directory: '/Test_output/log/bcftools.log'
```

From what I understand the call_log function try to write in the log/bcftools.log file, but don't create it. The file never exist and the function crash. It look like you should change the open() or create the file before.

Regards,
Jordi

**Comment by YuSugihara** [comment]
Thank you very much for reporting the error and I'm sorry for the late response.

I have recently found the error related to the python multiprocessing in bcftools:
https://github.com/YuSugihara/QTL-seq/issues/47
Depending on your error, version of QTL-seq, and os, this might resolve the issue.

The easiest check is to use the test dataset (https://github.com/YuSugihara/QTL-seq/tree/master/test).

The "call_log" function is called when the error occurs.
The error you reported is indeed the error, but this error occurred by another error.
