### ISSUE TITLE
!!ERROR!! tabix -f -p vcf qtl-seq_result2/30_vcf/qtlseq.Chr1.vcf.gz >> qtl-seq_result2/log/tabix.Chr1.log 2>&1

### ISSUE THREAD

**Issue by kmosi0** [YuSugihara/QTL-seq#6]
I came across an error，anyone got this problem too  and how to slove it ?  hope for you reply ，Thank you a lot . 
!!ERROR!! tabix -f -p vcf qtl-seq_result2/30_vcf/qtlseq.Chr1.vcf.gz >> qtl-seq_result2/log/tabix.Chr1.log 2>&1

please check below:

[QTL-seq:2020-06-22 20:03:31] !!ERROR!! tabix -f -p vcf qtl-seq_result2/30_vcf/qtlseq.Chr2.vcf.gz >> qtl-seq_result2/log/tabix.Chr2.log 2>&1

please check below:

[QTL-seq:2020-06-22 20:07:10] !!ERROR!! tabix -f -p vcf qtl-seq_result2/30_vcf/qtlseq.Chr4.vcf.gz >> qtl-seq_result2/log/tabix.Chr4.log 2>&1

please check below:

**Comment by kmosi0** [comment]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/zhanwei/project/20200103_yellow_white_Safflower_resequence_4X/QTL-seq/QTL-seq/qtlseq/mpileup.py", line 154, in mpileup
    check=True)
  File "/home/zhanwei/biosoft/Python_3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'tabix -f -p vcf qtl-seq_result2/30_vcf/qtlseq.Chr11.vcf.gz >> qtl-seq_result2/log/tabix.Chr11.log 2>&1' returned non-zero exit status 127.
