### ISSUE TITLE
!!ERROR!! bcftools mpileup 

### ISSUE THREAD

**Issue by hannyxie** [YuSugihara/QTL-seq#8]
I used it well before, but this time I don’t know what happened.
the version is qtlseq 2.1.2。
[QTL-seq:2020-09-08 00:03:05] [QTL-seq:2020-09-08 00:03:05] !!ERROR!! bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r chr03 -f stigma3/10_ref/IRGSP-1.0_genome.fasta --ignore-RG stigma3/20_bam/parent.filt.bam stigma3/20_bam/bulk1.filt.bam stigma3/20_bam/bulk2.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o stigma3/30_vcf/qtlseq.chr03.vcf.gz >> stigma3/log/bcftools.chr03.log 2>&1
please check below:

please check below:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/mpileup.py", line 144, in mpileup
    check=True)
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r chr09 -f stigma3/10_ref/IRGSP-1.0_genome.fasta --ignore-RG stigma3/20_bam/parent.filt.bam stigma3/20_bam/bulk1.filt.bam stigma3/20_bam/bulk2.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o stigma3/30_vcf/qtlseq.chr09.vcf.gz >> stigma3/log/bcftools.chr09.log 2>&1' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/mpileup.py", line 146, in mpileup
    call_log(self.out, 'bcftools', cmd1)
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/utils.py", line 20, in call_log
    with open('{}/log/{}.log'.format(out_dir, name)) as log:
FileNotFoundError: [Errno 2] No such file or directory: 'stigma3/log/bcftools.log'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xiehan1223/miniconda3/envs/bioinfo/bin/qtlseq", line 10, in <module>
    sys.exit(main())
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/qtlseq.py", line 173, in main
    QTLseq(args).run()
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/qtlseq.py", line 168, in run
    self.mpileup()
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/qtlseq.py", line 123, in mpileup
    mp.run()
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/mpileup.py", line 229, in run
    p.map(self.mpileup, chr_names)
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'stigma3/log/bcftools.log'stigma3/20_bam/parent.filt.bam stigma3/20_bam/bulk1.filt.bam stigma3/20_bam/bulk2.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o stigma3/30_vcf/qtlseq.chr03.vcf.gz >> stigma3/log/bcftools.chr03.log 2>&1
please check below:

please check below:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/mpileup.py", line 144, in mpileup
    check=True)
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bcftools mpileup -a AD,ADF,ADR -B -q 40 -Q 18 -C 50 -O u -r chr09 -f stigma3/10_ref/IRGSP-1.0_genome.fasta --ignore-RG stigma3/20_bam/parent.filt.bam stigma3/20_bam/bulk1.filt.bam stigma3/20_bam/bulk2.filt.bam | bcftools call -vm -f GQ,GP -O u | bcftools filter -i "INFO/MQ>=40" -O z -o stigma3/30_vcf/qtlseq.chr09.vcf.gz >> stigma3/log/bcftools.chr09.log 2>&1' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/mpileup.py", line 146, in mpileup
    call_log(self.out, 'bcftools', cmd1)
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/utils.py", line 20, in call_log
    with open('{}/log/{}.log'.format(out_dir, name)) as log:
FileNotFoundError: [Errno 2] No such file or directory: 'stigma3/log/bcftools.log'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xiehan1223/miniconda3/envs/bioinfo/bin/qtlseq", line 10, in <module>
    sys.exit(main())
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/qtlseq.py", line 173, in main
    QTLseq(args).run()
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/qtlseq.py", line 168, in run
    self.mpileup()
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/qtlseq.py", line 123, in mpileup
    mp.run()
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/site-packages/qtlseq/mpileup.py", line 229, in run
    p.map(self.mpileup, chr_names)
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/xiehan1223/miniconda3/envs/bioinfo/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'stigma3/log/bcftools.log'

**Comment by praneetha92** [comment]
Hi @hannyxie
I am facing this same error,can you please tell me how did you solve this problem?
QTL-seq version:-2.1.2

**Comment by hannyxie** [comment]
reinstall bcftools and make sure input sample name correctly
